---
title: "differential_expression_deseq2_Porites1"
author: "Natalia Andrade and Ira Cooke"
date: "07/08/2017"
output: html_document
---
---
title: "Coral Competition_Porites"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8,
                      echo=FALSE, warning=FALSE, message=FALSE)
knitr::opts_chunk$set(cache=TRUE)
options(width = 60)

library(knitr)
library(DESeq2)
library(stringr)
library(xlsx)
library(tidyverse)
library(ggrepel)
library(pheatmap)
library(dplyr)
```

First we prepare the data.  This involves reading in a counts matrix from corset.  Then we extract the sample names from the columns and match those to conditions in an excel file that describes the experimental conditions for each sample.

```{r without PdLd, echo=TRUE}
setwd("~/Dropbox/natalia_competition/Porites_competition/DESeq2")

# Counts obtained with `corset_alldifferent_genomics1.03.sh`

counts <- read_tsv("raw_data/03-counts.txt") %>% column_to_rownames(var="X1") %>% as.matrix()
#Elimitate de outlier: Pd:Ld
counts2 <- data.frame(counts) %>% select(-PdLd) %>% as.matrix()

sample_data <- read.csv("raw_data/Samples_data.csv",strip.white = T)
names(sample_data)

colnames(sample_data) <- c("ID","Tank","HardCoral",'treat',"SoftCoralControl","PCA")
head(sample_data)

sample_data_row_order <- match(colnames(counts2),sample_data$ID)

sample_data <- sample_data[match(colnames(counts2),sample_data$ID),]
sample_data<- sample_data %>% unite(HardCoralTrt,HardCoral,treat, remove=FALSE)

# This sets up the DESeq model

dds <- DESeqDataSetFromMatrix(countData = counts2,colData=sample_data,design = ~HardCoralTrt)
# Now we run the actual DESeq fitting process. 
# We do this twice. The first is a standard fit that will allow wald tests between specific conditions. 
# if the analysis was already run
if ( file.exists("data/dds.rds")){
  dds <- read_rds("data/dds.rds")
} else {
  dds <- DESeq(dds)
  write_rds(dds,"data/dds.rds")
}


# Contrast considering differences btw colonies and Treatment Control
resultsNames(dds)
#[1] "Intercept"        "HardCoralTrtPd_C" "HardCoralTrtPd_T" "HardCoralTrtPf_C" "HardCoralTrtPf_T"

res_TreatControl <- results(dds,contrast = c(0,-1,1,-1,1))
resOrdered_TreatControl <- as.data.frame(res_TreatControl[order(res_TreatControl$padj),]) %>% add_rownames("cluster_id") %>% filter(padj<0.1) # 193 genes DE
write.csv(resOrdered_TreatControl,"results/TreatControl_Porites_193.csv")


####### Principal componet analysis #########

vsd <- varianceStabilizingTransformation(dds, blind=FALSE)
pca_data <- plotPCA(vsd,intgroup=c("HardCoralTrt","SoftCoralControl"),returnData=TRUE)
ggplot(pca_data,aes(x=PC1,y=PC2)) + geom_point(aes(color=SoftCoralControl,shape=HardCoralTrt),size=4) + geom_label_repel(aes(label=group))  + theme(text = element_text(size=20))
  
# For genes DE ONLY in  contrast btw Control and treatment
names(resOrdered_TreatControl)

vsd <- varianceStabilizingTransformation(dds, blind=FALSE)
signif_genes <-  resOrdered_TreatControl[which(resOrdered_TreatControl$padj<0.1),]$cluster_id
select <- which(rownames(vsd) %in% signif_genes)
TreatvsControl <- assay(vsd)[select,]

write.table(TreatvsControl ,sep="\t",file = "results/TreatvsControl.txt",row.names = TRUE,quote = FALSE)
TreatvsControl<- read.csv("results/TvsC_193.csv", strip.white = T)
names(TreatvsControl) 
# Generate graphs 
newrownames<- TreatvsControl %>% dplyr::select(cluster_id)
new_data<- TreatvsControl
new_data<-reshape2::melt(new_data)
write.csv(new_data, "data/forplot_193.csv") 
# I edit table to have the different columns nedded for the graphs
forplot<-read.csv("data/forplot_193.csv", strip.white = TRUE)
names(forplot)
new_data<- forplot %>% arrange(cluster_id) %>% dplyr::slice(1:2123)
Plot_exp<-ggplot2::ggplot(data=new_data, aes(x=SoftCoral, y=value, colour=HardCoral)) + geom_point(aes(shape=Treat)) + facet_wrap(~cluster_id, scales = "free")  
pdf(file="results/Expression193_all.pdf",height =20,width = 20)

Plot_exp

#Heatmap for 193 genes
signif_genes <-  resOrdered_TreatControl[which(resOrdered_TreatControl$padj<0.1),]$cluster_id
select <- which(rownames(vsd) %in% signif_genes)
df <- as.data.frame(colData(dds)[,c("ID","SoftCoralControl","HardCoralTrt")])
heatmap_data <- assay(vsd)[select,order(df$HardCoralTrt)]
descriptions <- paste(rownames(heatmap_data))
rownames(heatmap_data) <- descriptions
# This writes the heatmap to a file.  
pdf(file="results/heatmap_193.pdf",height =20,width = 20)
pheatmap(heatmap_data, cluster_rows=TRUE, show_rownames=TRUE,cluster_cols=FALSE)
dev.off()  
```